/**
 * This file was automatically generated by Strapi.
 * Any modifications made will be discarded.
 */
import i18N from "@strapi/plugin-i18n/strapi-admin";
import usersPermissions from "@strapi/plugin-users-permissions/strapi-admin";
import strapiContentTypeExplorer from "strapi-content-type-explorer/strapi-admin";
import configSync from "strapi-plugin-config-sync/strapi-admin";
import importExportEntries from "strapi-plugin-import-export-entries/strapi-admin";
import multiSelect from "strapi-plugin-multi-select/strapi-admin";
import fieldUlid from "strapi-ulid/strapi-admin";
import { renderAdmin } from "@strapi/strapi/admin";

renderAdmin(document.getElementById("strapi"), {
  plugins: {
    i18n: i18N,
    "users-permissions": usersPermissions,
    "strapi-content-type-explorer": strapiContentTypeExplorer,
    "config-sync": configSync,
    "import-export-entries": importExportEntries,
    "multi-select": multiSelect,
    "field-ulid": fieldUlid,
  },
});
