name: Build Strapi and Deploy to Cloud Run

on:
  push:
    tags:
      - production/*
      - prod/*
      - development/*
      - dev/*

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ startsWith(github.ref, 'refs/tags/prod') && 'production' || 'development' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0

      - name: Use gcloud CLI
        run: gcloud info

      - name: Docker Auth
        uses: docker/login-action@v2
        with:
          username: _json_key
          password: ${{ secrets.GCP_KEY }}
          registry: ${{ vars.GAR_LOCATION }}-docker.pkg.dev

      - name: Build and Push Container
        run: |-
          docker build -t "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/cloud-run-source-deploy/${{ vars.SERVICE }}:${{ github.sha }}" .
          docker push "${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/cloud-run-source-deploy/${{ vars.SERVICE }}:${{ github.sha }}"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy \
            --image ${{ vars.GAR_LOCATION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/cloud-run-source-deploy/${{ vars.SERVICE }}:${{ github.sha }} \
            --region ${{ vars.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            ${{ vars.SERVICE }}
